server:
  port: 30100
  http2:
    enabled: true
spring:
  application:
    name: gpt-robot
  mvc:
    async:
      request-timeout: -1


gpt:
  key: ${gpt_key}
  uri: ${gpt_uri}
  model: ${gpt_model:gpt-3.5-turbo}

proxy:
  host: ${proxy_host}
  port: ${porxy_port}